name: Update Profile README

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Action dependencies
        working-directory: ./action
        run: npm ci

      - name: Run README updater
        uses: ./action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "chore: update activity snippet" || echo "No changes to commit"
          git push
